name: CI/CD

on:
# Khi push request được tạo trên nhánh master, workflow này sẽ được kích hoạt
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api
    strategy:
      matrix:
        node-version: [20]



    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install DI API
      run: npm ci

    - name: INSTALL DI FE
      run: npm ci
      working-directory: frontend

    - name: GENERATE PRISMA
      run: npx prisma generate
    # - name: LINT
    #   run: npm run lint || true
    
    - name: BUILD API
      run: npm run build

    - name: BUILD FE
      run: npm run build
      working-directory: frontend
    # - name: TEST
    #   run: npm test
  # deploy-api:
  #   name: Deploy
  #   run: ubuntu-latest
  #   needs: ci
  #   steps: 
  #     - uses: actions/checkout@v4